[build]
  command = "npm run build"
  publish = "public"

[[redirects]]
  from = "/bids/colorado"
  to = "/bids/colorado/"
  status = 301

[[redirects]]
  from = "/contractors/profile"
  to = "/contractors/profile.html"
  status = 200
